name: anthony_parking
description: "Parking system"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  intl: ^0.19.0
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  hive:
  hive_flutter:
  uuid: ^4.3.2
  gap: ^3.0.1
  shared_preferences: ^2.2.2
  flutter_form_builder: ^9.2.0
  mask_text_input_formatter: ^2.8.0
  google_ml_kit: ^0.16.3
  image_picker: ^1.0.7
  timezone: ^0.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - ./lib/assets/images/no_image_available.png
